application: appscaledashboard
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)


- url: /js
  static_dir: js

- url: .*
  script: docs.app

libraries:
- name: webapp2
  version: latest
